<template>
<div class="flex flex-col justify-center items-center text-center my-8">
    <h1 class="font-Lobster text-4xl text-black">{{ title}}</h1>
    <div style="display: flex; margin-left: -5.5rem;"><svg xmlns="http://www.w3.org/2000/svg" width="120.112" height="50" viewBox="0 0 207.112 66" style="fill: none; stroke: rgb(35, 83, 159); stroke-linecap: round; stroke-width: 11px;"><defs><filter id="a" x="0" y="0" width="207.112" height="66" filterUnits="userSpaceOnUse"><feOffset dy="3" input="SourceAlpha"></feOffset><feGaussianBlur stdDeviation="9.5" result="b"></feGaussianBlur><feFlood flood-color="#fff"></feFlood><feComposite operator="in" in2="b"></feComposite><feComposite in="SourceGraphic"></feComposite></filter></defs><g transform="matrix(1, 0, 0, 1, 0, 0)"><path d="M859.5,1043.626h141.112" transform="translate(-826.5 -1013.63)"></path></g></svg><svg xmlns="http://www.w3.org/2000/svg" width="50.002" height="50" viewBox="0 0 100.002 66" style="fill: none; stroke: rgb(35, 83, 159); stroke-linecap: round; stroke-width: 11px;"><defs><filter id="a" x="0" y="0" width="100.002" height="50" filterUnits="userSpaceOnUse"><feOffset dy="3" input="SourceAlpha"></feOffset><feGaussianBlur stdDeviation="9.5" result="b"></feGaussianBlur><feFlood flood-color="#fff"></feFlood><feComposite operator="in" in2="b"></feComposite><feComposite in="SourceGraphic"></feComposite></filter></defs><g class="b" transform="matrix(1, 0, 0, 1, 0, 0)"><path class="a" d="M859.5,1043.626h34" transform="translate(-826.5 -1013.63)"></path></g></svg><svg xmlns="http://www.w3.org/2000/svg" width="30.75" height="50" viewBox="0 0 73.75 66" style="fill: none; stroke: rgb(35, 83, 159); stroke-linecap: round; stroke-width: 11px;"><defs><filter id="a" x="0" y="0" width="73.75" height="66" filterUnits="userSpaceOnUse"><feOffset dy="3" input="SourceAlpha"></feOffset><feGaussianBlur stdDeviation="9.5" result="b"></feGaussianBlur><feFlood flood-color="#fff"></feFlood><feComposite operator="in" in2="b"></feComposite><feComposite in="SourceGraphic"></feComposite></filter></defs><g class="b" transform="matrix(1, 0, 0, 1, 0, 0)"><path class="a" d="M859.5,1043.626h7.75" transform="translate(-826.5 -1013.63)"></path></g></svg></div>
</div>
</template>
<script>
export default {
    props:['title']
}
</script>